### PR TITLE
Translate to English

### PR DESCRIPTION
**Pull request by katrinleinweber**
### Open questions & points to discuss

- Translation does create the impression of wanting to reach-out to a wider audience. If so, the `References` table could be sorted by angel number, instead of chronologically.
- For a more compact impression, `Event` and `Angels` columns could be switched

### CODE REVIEW

**Comment by msquare** [comment]
The references should also advertise the events. If we sort by number of angels, the small events are at the bottom - which means bad advertising. I would like to keep the table chronologically.

You can also add the newest event, Easterhegg 2017 in Mühlheim am Main, https://eh17.easterhegg.eu/

**Comment by katrinleinweber** [comment]
Yes, but would argue that in the international context the event advertisement function is less useful than highlighting the _range_ of event sizes. Plus, most of the events are over, and upcoming ones are advertised elsewhere in a better fashion.

**Comment by msquare** [comment]
What about adding the scalability as a feature/fact to the feature list?
"Skaliert problemlos auf tausende Helfer und zehntausende Schichtstunden"

If you have an idea how to present multiple upcoming events in a better fashion (like now there is only place for one upcoming event), feel free to implement. Just do it as you like.

**Comment by katrinleinweber** [comment]
My thinking as well :-)   But I'll do that on different branches.

**Pull request merged**
